POST http://localhost:5000/register
Content-Type: application/json

{
    "username": "kofiadu",
    "password": "12345"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "username": "kofiadu",
    "password": "12345"
}

###
GET http://localhost:5000/api/details
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJRCI6NiwiaWF0IjoxNjk0MTY3NTY4LCJleHAiOjE2OTQxNzQ3Njh9.lYhl5BrFjIECQIYgIYub6yfiMh3kx3NsF3LXN5TI8PA

###
POST http://localhost:5000/api/add
Content-Type: application/json
Authorization:  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJRCI6NiwiaWF0IjoxNjk0MTY3NTY4LCJleHAiOjE2OTQxNzQ3Njh9.lYhl5BrFjIECQIYgIYub6yfiMh3kx3NsF3LXN5TI8PA

{
    "fullname": "Mehdi",
    "favouriteCountry": "France",
    "favouriteTeam": "French National Team",
    "favouritePlayer": "Didier Deschamps",
    "favouriteCoach": "Alegri"
}

###
PATCH http://localhost:5000/api/edit/3
Content-Type: application/json
Authorization:  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJRCI6NiwiaWF0IjoxNjk0MTY3NTY4LCJleHAiOjE2OTQxNzQ3Njh9.lYhl5BrFjIECQIYgIYub6yfiMh3kx3NsF3LXN5TI8PA

{
    "fullname": "Mehdi Belila"
}

###
DELETE http://localhost:5000/api/delete/3
Content-Type: application/json
Authorization:  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJRCI6NiwiaWF0IjoxNjk0MTY3NTY4LCJleHAiOjE2OTQxNzQ3Njh9.lYhl5BrFjIECQIYgIYub6yfiMh3kx3NsF3LXN5TI8PA
